### ISSUE TITLE
Investigate unique attacks based on weapon type equipped

### ISSUE THREAD

**Issue by JOMO21** [JOMO21/GWRPGMaker#25]
- Axe: Swift Chop
Axe Attack. Deals +x damage. Deals x damage and inflicts Deep Wound condition (x turns) if blocked.

- Sword: 

- Hammer: 

- Holy Staff: Place state on ally that lasts one turn. When state ends, heal target ally for x hp.

- Protective Staff: place state on ally for 1 turn. They block the next attack.
https://forums.rpgmakerweb.com/index.php?threads/ap-blocking.66052/

- Smiting Staff: Deal holy damage to one enemy. If target is undead, inflict burning for x turns

- Water Staff: Place state on enemy that makes them more vulnerable to cold damage for x turns.

- Fire Staff: Deal x fire damage to all enemies.

- Air Staff: Deal x lightning damage to enemy. Has a % chance to apply blind state for x turns.
https://forums.rpgmakerweb.com/index.php?threads/inflict-state-after-attack-with-chance.88137/

- Earth Staff: Place state on all allies for x turns. While state is active, they have increased def.

- Blood Magic Staff: place state on ally for 1 turn. While state is active, they steal some hp with their next attack.

- Curses staff: Place state on enemy for x turns. While state is active, enemy has decreased hit% but increased attack and magic attack

- Death Magic Staff: Deal x dark damage to enemy. Has a x% chance to place state on enemy for 1 turn. If an enemy is killed while state is active, summon a bone minion ally.
In death staff state notebox
<Custom Turn Start Effect>
if (user.isStateAffected(1)) {
summon bone minion
}

- Illusion Magic Staff:

- Domination Staff: 

- Inspiration Staff:

- Holy Wand:

- Protective Wand:

- Smiting Wand:

- Fire Wand:

- Water Wand:

- Air Wand:

- Earth Wand:

- Recurve Bow:

- Horn Bow:

- Longbow:

- Flatbow:

- Shortbow:

**Comment by Hour-of-the-Owl** [comment]
axe: if you hit, X% chance to inflict Deep Wound for Y turns
flatbow: if you hit, X% chance to deal double damage; Y% chance to miss
hammer: if you hit, X% chance to KD
hornbow: if you hit, X% chance to inflict Bleeding for Y turns
longbow: if you hit, X% chance to inflict Cripple for Y turns.
recurve bow: if you hit, X% chance to inflict Dazed for Y turns
shortbow: X% chance to shoot two arrows
sword: if you hit, X% chance to gain +1 Adrenaline

air staff/wand: X% chance to bounce to another foe
blood staff/wand: if you hit, steal Y health from target
curses staff/wand: if you hit, X% chance to inflict Poison for Y turns
death staff/wand: if you hit, X% chance to inflict Disease for Y turns
domination staff/wand: if you hit, X% chance to interrupt target's current action
earth staff/wand: if you hit, X% chance to inflict Weakness for Y turns
fire staff/wand: if you hit, X% chance to inflict Burning for Y turns
healing staff/wand: X% chance to heal your party for Y
illusion staff/wand: if you hit, X% chance to hex target with Conjure Nightmare (-Z degen) for Y turns
inspiration staff/wand: if you hit, X% chance to gain Y energy
protection staff/wand: enchant your party with Aegis (X% chance to block attacks) for 1 turn
smiting staff/wand: if you hit, X% chance to hex target with Pacifism (unable to attack) for 1 turn
water staff/wand: if you hit, X% chance to inflict Cracked Armor for Y turns

**Comment by Hour-of-the-Owl** [comment]
I wrote some descriptions, each referencing an appropriate GW skill!

axe: Swiftly chop target foe. If you hit, X% chance to inflict a Deep Wound for Y turns.
flatbow: Fire an arcing shot at target foe, with a Y% chance to miss. If you hit, X% chance to deal double damage.
hammer: Bash target foe with your hammer. If you hit, X% chance to knock down.
hornbow: Fire a screaming shot at target foe. If you hit, X% chance to inflict Bleeding for Y turns.
longbow: Fire a crippling shot at target foe. If you hit, X% chance to inflict Cripple for Y turns.
recurve bow: Fire a broadhead arrow at target foe. If you hit, X% chance to inflict Dazed for Y turns.
shortbow: Fire a dual shot at target foe. If you hit, X% chance to hit twice.
sword: Slash target foe like a dragon. If you hit, X% chance to gain +1 Adrenaline.
^ yeah okay that one looks a bit dodgy xD better suggestions?

air staff/wand: Attack target foe with your staff/wand. X% chance to invoke lightning, attacking another foe.
^ this one probably needs better explanation to make it clear that it can keep attacking as long as it gets the X% RNG
blood staff/wand: Attack target foe with your staff/wand. If you hit, drink their blood, stealing Y health.
curses staff/wand: Attack target foe with your staff/wand. If you hit, X% chance to envenom them, inflicting Poison for Y turns.
death staff/wand: Attack target foe with your staff/wand. If you hit, X% chance to rot their flesh, inflicting Disease for Y turns
domination staff/wand: Attack target foe with your staff/wand. If you hit, X% chance to panic them, interrupting their current action.
earth staff/wand: Attack target foe with your staff/wand. If you hit, X% chance to stone them, inflicting Weakness for Y turns.
fire staff/wand: Attack target foe with your staff/wand. If you hit, X% chance to immolate them, inflicting Burning for Y turns.
healing staff/wand: Attack target foe with your staff/wand. X% chance to heal your party for Y.
illusion staff/wand: Attack target foe with your staff/wand. If you hit, X% chance to conjure a nightmare, inflicting -Z degen for Y turns
inspiration staff/wand: Attack target foe with your staff/wand. If you hit, X% chance to drain their power, stealing Y energy.
protection staff/wand: Attack target foe with your staff/wand. Your party is enchanted with Aegis (X% chance to block attacks) for 1 turn.
smiting staff/wand: Attack target foe with your staff/wand. If you hit, you have a X% chance to pacify them for 1 turn, making them unable to attack.
water staff/wand: Attack target foe with your staff/wand. If you hit, X% chance to freeze their mind, inflicting Cracked Armor for Y turns.
^ sure, Mind Freeze doesn't really inflict cracked armor, but nothing in Water Magic does. In fact, that whole attribute is mostly just stuff that doesn't apply to this game, which is why I gave it something different.
